# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=5)),
                ('depart_city', models.CharField(max_length=20)),
                ('destination_city', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'landed', b'landed'), (b'landing', b'landing'), (b'take_off', b'take_off'), (b'detained', b'detained')], default=b'landed', max_length=10)),
            ],
        ),
    ]
